### Primeiro teste
POST http://localhost:3333/trips
Content-Type: application/json

{
    "destination": "Florianópolis",
    "starts_at": "2024-06-01 18:00:00",
    "ends_at": "2024-06-15 18:00:00"
}

### Verificar se as datas são válidas
POST http://localhost:3333/trips
Content-Type: application/json

{
    "destination": "Florianópolis",
    "starts_at": "2024-07-10 18:00:00",
    "ends_at": "2024-07-08 18:00:00"
}

### Teste do nodemailer
POST http://localhost:3333/trips
Content-Type: application/json

{
    "destination": "Florianópolis",
    "starts_at": "2024-07-20 18:00:00",
    "ends_at": "2024-07-30 18:00:00",
    "owner_name": "ryandvl",
    "owner_email": "contact@ryandvl.com",
    "emails_to_invite": [
        "ryandvl@gmail.com",
        "johndoe@gmail.com"
    ]
}

### Criar viagem
POST http://localhost:3333/trips/06d6c90b-5f94-471b-8c60-c3581f2dab56/activities
Content-Type: application/json

{
    "title": "Academia",
    "occurs_at": "2024-07-11 09:00:00"
}

### Pegar a lista de atividadades
GET http://localhost:3333/trips/06d6c90b-5f94-471b-8c60-c3581f2dab56/activities

### Pegar a lista de links
GET http://localhost:3333/trips/06d6c90b-5f94-471b-8c60-c3581f2dab56/links
